### ISSUE TITLE
ImportError: No module named 'cpp_functions' in windows 10, different error.

### ISSUE THREAD

**Issue by ghost** [DIAGNijmegen/pathology-streaming-pipeline#3]
Hello,

Also thank you from my side for sharing this repository.
Similar to @jeroenmollink (issue #2 ) I have struggle to load the cpp_functions.

I am using Anaconda with python 3.6 on windows 10. I am using torch version 1.6 (nightly) as torch 1.5 and torch 1.4 do not have autocast.

Visual Studio 2017 is installed and made available via command line. I also installed ninja 1.9.0.

When I execute train.py, the following error occurs:
ninja: error: loading 'build.ninja': The system cannot find the file specified.

Traceback (most recent call last):
  File "C:/Targos_AI/pathology-streaming-pipeline/streaming/train.py", line 23, in <module>
    from torch_utils.streaming_trainer import \
  File "C:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\streaming_trainer.py", line 6, in <module>
    from .scnn import StreamingCNN
  File "C:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\scnn.py", line 48, in <module>
    cpp_functions = load(name="cpp_functions", sources=[filename], verbose=True,build_directory=dirname)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 902, in load
    keep_intermediates=keep_intermediates)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1107, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1174, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1225, in verify_ninja_availability
    if not _is_ninja_available():
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1213, in _is_ninja_available
    subprocess.check_call('ninja -v'.split(), stdout=devnull)
  File "C:\Anaconda\TARGOS_AI\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I read that there is an issue with ninja commands in windows. Accordingly I changed line 1395 in file C:\Anaconda\TARGOS_AI\Lib\site-packages\torch\utils\cpp_extension.py (command = ['ninja', '-v']) to command = ['ninja', '--version'].

The above shown error disappeared but instead a new error occurred, very similar to that described by @jeroenmollink (issue #2 )

Emitting ninja build file C:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\build.ninja...
Building extension module cpp_functions...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.9.0
Traceback (most recent call last):
  File "C:/Targos_AI/pathology-streaming-pipeline/streaming/train.py", line 23, in <module>
    from torch_utils.streaming_trainer import \
  File "C:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\streaming_trainer.py", line 6, in <module>
    from .scnn import StreamingCNN
  File "C:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\scnn.py", line 48, in <module>
    cpp_functions = load(name="cpp_functions", sources=[filename], verbose=True,build_directory=dirname)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 902, in load
    keep_intermediates=keep_intermediates)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1118, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Anaconda\TARGOS_AI\lib\site-packages\torch\utils\cpp_extension.py", line 1439, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Anaconda\TARGOS_AI\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'cpp_functions'
Loading extension module cpp_functions...

As suggested, I edited the cpp_functions.cpp file but without any changes. The error remained the same. 
I assume that there might be some wrongly defined path, caused by the fact that I am logged in to the computer via my user credentials but use an anaconda instance which is installed globally.
I don't know if this might be the reason, but when I try to debug my code, I find unexpected variable values (see screenshot)
![image](https://user-images.githubusercontent.com/62333302/87781978-f3f39100-c831-11ea-88f8-f36f2a68d376.png)
I am not familiar with the cpp_extension.py function, therefore I don't know if itis unusual that the path variable is linked to my user path.

However, the input parameter of the torch.utils.cpp_extension.load function contain the path to the cpp_function.cpp file (Screenshot)
![image](https://user-images.githubusercontent.com/62333302/87782262-7da35e80-c832-11ea-8092-a02251e19d3e.png)

I am glad for any suggestions,

Stefan

**Comment by ghost** [comment]
Below I posted the context of the build.ninja file. Maybe it can helpt to identify the error.

ninja_required_version = 1.3
cxx = C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe

cflags = -DTORCH_EXTENSION_NAME=cpp_functions -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Anaconda\TARGOS_AI\lib\site-packages\torch\include -IC:\Anaconda\TARGOS_AI\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda\TARGOS_AI\lib\site-packages\torch\include\TH -IC:\Anaconda\TARGOS_AI\lib\site-packages\torch\include\THC -IC:\Anaconda\TARGOS_AI\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /EHsc
post_cflags = 
ldflags = /DLL c10.lib torch_cpu.lib torch.lib torch_python.lib /LIBPATH:C:\Anaconda\TARGOS_AI\libs /LIBPATH:C:\Anaconda\TARGOS_AI\lib\site-packages\torch\lib

rule compile
  command = cl /showIncludes $cflags -c $in /Fo$out $post_cflags
  deps = msvc

rule link
  command = "C$:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64/link.exe" $in /nologo $ldflags /out:$out

build cpp_functions.o: compile C$:\Targos_AI\pathology-streaming-pipeline\streaming\torch_utils\cpp_functions.cpp

build cpp_functions.pyd: link cpp_functions.o

default cpp_functions.pyd

**Comment by hanspinckaers** [comment]
I don't think you can change ninja -v to ninja --version? At least in Linux, those flags mean different things, see; http://manpages.ubuntu.com/manpages/cosmic/man1/ninja.1.html 

Did you find this change on the web somewhere?

Also strange: the ninja build file looks OK I think.

**Comment by ghost** [comment]
I found the idea of changing ninja -v to ninja --version here: https://github.com/nv-tlabs/GSCNN/issues/15

But you are right, they are different commands

**Comment by hanspinckaers** [comment]
Okay, I don't know a lot about Windows. However, it seems to compile to a 'cpp_functions.pyd' file and that, I think, depends on a DLL file somewhere. PyTorch seems to put the files in the `temp/torch_extensions/cpp_functions` location. Maybe you can just copy the files in that directory to the torch_utils folder? And change the import? 

So try to comment out:
https://github.com/DIAGNijmegen/pathology-streaming-pipeline/blob/add72bd993cbd590a1cbe2b253a5ee4328de08d5/streaming/torch_utils/scnn.py#L40-L43 

And add:
```python
from cpp_functions import *
```

**Comment by hanspinckaers** [comment]
Ah it seems like the .pyd file _is_ the dll file, maybe that file is all you need then: 
https://docs.python.org/3/faq/windows.html#is-a-pyd-file-the-same-as-a-dll

**Comment by ghost** [comment]
I finally found my mistakes. 
The errors were caused by missing environmental variables. Ninja was not able to create the cpp_functions.pyd etc. files. In consequence, the cpp_functions file could not be loaded.

I had to set the following environmental variables:
PATH:
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86
INCLUDE:
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include
•	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt
•	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared
LIB
•	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\onecore\x64
•	C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64
•	C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64

Next, I executed the command line command:
ninja -f "C:\Users\DE1119177\AppData\Local\Temp\torch_extensions\cpp_functions\build.ninja"

This command created the following files: 
![image](https://user-images.githubusercontent.com/62333302/87943845-e55de180-ca9e-11ea-892f-55f4d4ae5ee1.png)

Unfortunately, these files where not created to the correct directory for the cpp load function to be found. However, I copied the created files to "C:\Users\DE0000\AppData\Local\Temp\torch_extensions\cpp_functions" and executed the python function _train.py_ again. The cpp files were loaded successfully.


**Now I face a different, windows 10 based problem:**
'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Targos_AI/pathology-streaming-pipeline/streaming/train.py", line 498, in <module>
    if distributed: torch.distributed.init_process_group(backend='nccl', init_method='env://')  # type:ignore
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
Starting 0 of n gpus: 4

Process finished with exit code 1


It seems that pytorch does not support multiple GPUs under windows. **However, this is a different issue.**

Thank you very much for your help and your repository.
